### ISSUE TITLE
Invalid HTML results in request error

### ISSUE THREAD

**Issue by tommedema** [luin/readability#53]
When I pass in the following string as HTML:

		��ZYSY�~vG��N��mkE��ծ*��,1[��D��J%H��de �'&amp;B�;����Xe���t��L=�_�s��I,���5�Gh��.��{�w�=�k�}8�K�I��H]����]+�3=]��ؒ ���G$)��p$�Bܞ����Ot92�?g������ q�R� ٴ�q�Ϟ&gt;O�%!Ͽ�hg���_B��g�7��Z�;&quot;ġ����[,纄 ˥�H&quot;�2�
		���ЛI��&quot;���6��2aA�SѤM����RLh#�?(�����ϑ\V.��ܒ���r�U^�ե���~2&gt;�@9xM�'�� C/�M������sus��A[�j�J�Og%&gt;����_.&amp;H�L����N�WȮ�Jn\=��H����|8&quot;K�ђ2&gt;!�Sm�:��C���dU�E���HJ���*��]�v�^_C���d����p;]^���q�RoLptq�$���ӛbAV,FAb\�AVz$�'��s�\7G�����M2��ٿ��+:\v��c�+�m�Z�6��/j�V��h��s���usp�(J�
		a �Ѽj%������\w��?U ��I|Zb�9Uj�F�R�h����gء�0v�|(�����oܨ�&quot;s�*1�f�� kX(�`�E�ޅ�pE���5��U�R]��v�)�ru����L�K��l�h�ʕV�XhW�n�z{�c�N�n�A���&gt;k��2���r����ui������s0���te��;ک.�sr�mr�))�7�ꀑ��0/P/���M�Xjuv�^&quot;��V0�:#x�F��NAtD�.{2��2\Vν��G���B�����Pˎ(�������f�P���Y/��s[}W7
		Ib�|����d���쾮ϒ�ESC0�g��wqQ@{0�l8*&amp;c\oK(����2;��j�z��wWZ�F�d{BY��M�p&quot;��ԍ�6�Gv6�em��|�@��H�ee� �'Α�&gt;mgC&gt;&amp;c$7O�%��oJ�ձ](o&gt;Q����TW^l*c#��2 (Y��ȓ�q��|M �ɬ\�Q�_�.@$�y����E�Ѡϣd�e%;��В�FeeRYX�޵������#�?1������ 'r�G�v�L畭u�;ڑ��@{����K�0&quot;e����Z��#m�-9�QA-h��J�k�\�:
		|&quot;�H�0�ΐ���^g����d����^�m|Gr�?�A��P���?��c �k����C���5rv���l���N�Ŝ�c��&amp;�j�ET�9\Quk�;�n�BB�Ίz�q���Q#����]�t|�N���� t�\׺��@���|��} �D;.ʠ�Zg���q�A�X,��6���O B6�TZ`��i.�za��vFX&amp; K� ���2�]����T�튆�1���-��s��].��z�-�K&amp;cQ�C���sC��yd�n��#b?]�0n�).���
		�SW�Pu���ԚR�O��.&amp;�$k�Z%7A��`9�����ۢ�M��g��ֺѰ�i3�_m�g���UX�d~�4mV̻tj��r?�ˡ.����2|r��Ll讎�]=���xǶQ���-��jůǭZ%�&quot;���G O��E�8��`_���ce��:�������8��-Wf^RLS7�M�|��aHߖ�� ��l�+/fԭ-��UfKZ���=�&quot;��2��2�DN�?���&amp;��Nh�:���ϸ���ީ)~���SQ���)/Iy_$�����Z!��\&amp;C�ri!kf\.��#�=((F'��a����3$�i�p�J�r)��G��{������G��3U������=o�������z�虆qz��Ĝ���:6L޾��@�o��K�
		�}�5� �MO����&gt;Cߧ}�a��@_ ��^�W���\��|����1���T��rq�4]t����g zaK�0�����cp+�����U��.�����LJS�N}�R �K-�C,�du���}g�r�P�ryˌ��WZ��M�CT�����Hr�Џ��� �B��� ���|j�D�'?AZ� F��)�%�G�������@/�MAP��| ����\T�g����H;  g�I�sP]Ɏ)Ko��dr�R�UC�����b��p`jC��a��3���(:�crqH&gt;\��#�SB࿲��^c�hgN=yA|����9C�L�a�w�D�:y'�q|���i���R�#�
		Cm(T����� W���4�ɿ��Ûzwfl�6���lL���L��9#�p����7�����M�4;�w������9#�ҙ0��z!�s���E�a��&amp;KnIq�=�!@�0Z��.����`���Ä�&amp;Hߦ6�D]\�#��;7'R�����&gt;,*#���)!d��ˡ7�Ќ��5s0��Q?�Y�(�4��K�����#|I���u��c��L.Α��Iep�

It should return an empty string as readable content, but instead I get:

		[2015-06-30 18:57:57.560] [ERROR] [default] - { [Error: Invalid protocol: null] cause: [Error: Invalid protocol: null], isOperational: true }
		Error: Invalid protocol: null
		    at Request.self._buildRequest (/home/tom/projects/project/project-pce/node_modules/node-readability/node_modules/request/request.js:355:53)
		    at Request.init (/home/tom/projects/project/project-pce/node_modules/node-readability/node_modules/request/request.js:533:10)
		    at new Request (/home/tom/projects/project/project-pce/node_modules/node-readability/node_modules/request/request.js:99:8)
		    at request (/home/tom/projects/project/project-pce/node_modules/node-readability/node_modules/request/index.js:54:11)
		    at Function.read (/home/tom/projects/project/project-pce/node_modules/node-readability/src/readability.js:170:5)
		    at Function.tryCatcher (/home/tom/projects/project/project-pce/node_modules/bluebird/js/main/util.js:24:31)
		    at ret (eval at <anonymous> (/home/tom/projects/project/project-pce/node_modules/bluebird/js/main/promisify.js:155:12), <anonymous>:14:23)
		    at extractContent (/home/tom/projects/project/project-pce/app/index.js:34:10)
		    at tryCatcher (/home/tom/projects/project/project-api/node_modules/bluebird/js/main/util.js:24:31)
		    at Promise._settlePromiseFromHandler (/home/tom/projects/project/project-api/node_modules/bluebird/js/main/promise.js:452:31)
		    at Promise._settlePromiseAt (/home/tom/projects/project/project-api/node_modules/bluebird/js/main/promise.js:530:18)
		    at Promise._settlePromises (/home/tom/projects/project/project-api/node_modules/bluebird/js/main/promise.js:646:14)
		    at Async._drainQueue (/home/tom/projects/project/project-api/node_modules/bluebird/js/main/async.js:182:16)
		    at Async._drainQueues (/home/tom/projects/project/project-api/node_modules/bluebird/js/main/async.js:192:10)
		    at Immediate.Async.drainQueues [as _onImmediate] (/home/tom/projects/project/project-api/node_modules/bluebird/js/main/async.js:15:14)
		    at processImmediate [as _immediateCallback] (timers.js:358:17)

It seems like it is misinterpreting this string as an URL and passing it to `request`?

**Comment by tommedema** [comment]
Much appreciated.
